# Generated by Django 6.0.5 on 2026-05-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='categoria',
            field=models.CharField(choices=[('cftv', 'CFTV'), ('portaria_remota', 'Portaria Remota'), ('rede_internet', 'Rede/Internet'), ('controle_acesso', 'Controle de Acesso'), ('interfone', 'Interfone'), ('manutencao', 'Manutenção'), ('outro', 'Outro')], default='outro', max_length=50),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='prioridade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20),
        ),
    ]
