# Generated by Django 6.0.5 on 2026-05-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_chamado_categoria_alter_chamado_prioridade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='chamado',
            name='prioridade',
        ),
        migrations.AddField(
            model_name='chamado',
            name='urgente',
            field=models.BooleanField(default=False),
        ),
    ]
