# Generated by Django 6.0.5 on 2026-05-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_remove_chamado_categoria_remove_chamado_prioridade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='chamados/'),
        ),
    ]
