# Generated by Django 6.0.5 on 2026-05-28 15:20

from django.db import migrations, models


def preencher_resolvidos(apps, schema_editor):
    chamado = apps.get_model('tickets', 'Chamado')
    chamado.objects.filter(
        status='resolvido',
        resolvido_em__isnull=True,
    ).update(resolvido_em=models.F('criado_em'))


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_chamado_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='resolvido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            preencher_resolvidos,
            migrations.RunPython.noop,
        ),
    ]
