# Generated by Django 6.0.5 on 2026-05-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_chamado_criado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='descricao_resolucao',
            field=models.TextField(blank=True),
        ),
    ]
